---

- name: "Install php-fpm"
  package:
    state: present
    name : "{{ php_version }}-php-fpm"

- name: "Configure tmpfiles.d for /run/php-fpm"
  copy:
    dest: /etc/tmpfiles.d/php-fpm.conf
    content: 'd /run/php-fpm 755 root root'
    owner: root
    group: root
    mode: 0644

- name: "Create /run/php-fpm directory"
  file:
    path: /run/php-fpm
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "Change default pool to use unix socket"
  replace:
    path: /etc/opt/remi/{{ php_version }}/php-fpm.d/www.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - regexp: 'listen = 127.0.0.1:9000'
      replace: 'listen = /run/php-fpm/www-{{ php_version }}.sock'
    - regexp: ';listen.owner = nobody'
      replace: 'listen.owner = apache'
    - regexp: ';listen.group = nobody'
      replace: 'listen.group = apache'

- name: "Ensure pool user exists"
  user:
    state: present
    name: "{{ item.name }}"
    home: "{{ item.user_home | default('/var/www/vhosts/' + item.name) }}"
    append: yes
  loop: "{{ php_fpm_pools }}"

- name: "Set permissions for homedir of pool user"
  file:
    state: directory
    path: /var/www/vhosts/{{ item.name }}
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0750
  loop: "{{ php_fpm_pools }}"

- name: "Create tmp directory for pool user"
  file:
    state: directory
    path: /var/www/vhosts/{{ item.name }}/tmp
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0750
  loop: "{{ php_fpm_pools }}"

- name: "Add apache to pool user group"
  user:
    state: present
    name: apache
    groups:
      - "{{ item.name }}"
    append: yes
  loop: "{{ php_fpm_pools }}"

- name: "Copy default pool config"
  template:
    src: pool.default.j2
    dest: /etc/opt/remi/{{ php_version }}/php-fpm.d/pool.default
    owner: root
    group: root
    mode: 0644

- name: "Create additional php-fpm pools"
  template:
    src: pool.conf.j2
    dest: /etc/opt/remi/{{ php_version }}/php-fpm.d/{{ item.name }}.conf
    owner: root
    group: root
    mode: 0644
  notify: "restart_php_fpm"
  loop: "{{ php_fpm_pools }}"
