---
# tasks file for tamay.php

- name: "Enable remi repository"
  package:
    state: present
    name: https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm

- name: "Install RPM-GPG-KEY-remi"
  rpm_key:
    state: present
    key: https://rpms.remirepo.net/RPM-GPG-KEY-remi

- name: "Add php modules to list"
  set_fact:
    php_packages: "{{ php_packages }} + ['{{ php_version }}-php-{{ item }}']"
  loop: "{{ php_modules }}"

- name: "Install php packages"
  package:
    state: present
    name: "{{ php_packages }}"

- name: "Create symlink from /opt/remi/{{ php_version }}/root/usr/bin/php to {{ php_symlink }}"
  file:
    state: link
    src: /opt/remi/{{ php_version }}/root/usr/bin/php
    dest: "{{ php_symlink_path }}"
  when: php_symlink

- name: "Configure php.ini"
  template:
    src: 50-custom.ini.j2
    dest: /etc/opt/remi/{{ php_version }}/php.d/50-custom.ini
    owner: root
    group: root
    mode: 0644

- name: "Configure opcache"
  replace:
    path: /etc/opt/remi/{{ php_version }}/php.d/10-opcache.ini
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - regexp: '.?opcache\.enable=\d'
      replace: 'opcache.enable={{ php_opcache_config.enable }}'
    - regexp: '.?opcache\.enable_cli=\d'
      replace: 'opcache.enable_cli={{ php_opcache_config.enable_cli }}'
    - regexp: '.?opcache\.memory_consumption=\d+'
      replace: 'opcache.memory_consumption={{ php_opcache_config.memory_consumption }}'
    - regexp: '.?opcache\.interned_strings_buffer=\d+'
      replace: 'opcache.interned_strings_buffer={{ php_opcache_config.interned_strings_buffer }}'
    - regexp: '.?opcache\.max_accelerated_files=\d+'
      replace: 'opcache.max_accelerated_files={{ php_opcache_config.max_accelerated_files }}'
    - regexp: '.?opcache\.save_comments=\d'
      replace: 'opcache.save_comments={{ php_opcache_config.save_comments }}'
    - regexp: '.?opcache\.revalidate_freq=\d'
      replace: 'opcache.revalidate_freq={{ php_opcache_config.revalidate_freq }}'
    - regexp: '.?opcache\.fast_shutdown=\d'
      replace: 'opcache.fast_shutdown={{ php_opcache_config.fast_shutdown }}'

- import_tasks: fpm.yml
  when: php_fpm
